### ISSUE TITLE
CI: automatically create the system and api docs in travis ci and upload them to gh pages

### ISSUE THREAD

**Issue by hstolte** [TouchTheBeat/Backend#39]

**Comment by ErdnussFlipS** [comment]
firstly uploaded to ftp server

**Comment by hstolte** [comment]
Please update the readme with the urls to the documentations before closing this issue.

**Comment by ErdnussFlipS** [comment]
The issue does not declare to add links to the readme.  Therefore the issue can closed. Furthermore, I add the links to the readme.
