### ISSUE TITLE
Implement continuous deployment

### ISSUE THREAD

**Issue by hstolte** [TouchTheBeat/Backend#42]
...so that the current build does not need to be uploaded via ftp manually after every commit.

**Comment by hstolte** [comment]
The current build is not yet working. It responds with an error 404 on ``GET system/codes```.

**Comment by ErdnussFlipS** [comment]
Can closed. Your comment not aimes this issue.

**Comment by ErdnussFlipS** [comment]
Your comment is fixed by the latest build.
