### ISSUE TITLE
The values of the levels audio property are incorrect

### ISSUE THREAD

**Issue by hstolte** [TouchTheBeat/Backend#53]
After creating a new level with ``POST level`` and then fetching it with ``GET level``, the ``audio`` information was changed and is incorrect:

The ``audio.title`` attribute seems to have the value of the original SoundCloud resources ``permalink``attribute instead of the ``title`` attribute. Also, the ``audio.artist`` attribute has the value of ``user.permalink`` instead of ``user.username``. The ``audio.duration`` attribute has a completely different value (I have no idea of its origin.).

The route ``GET audio/soundcloud`` seems to be not affected by this and still returns the original SoundCloud resource.

Found when searching for bugs manually (https://github.com/TouchTheBeat/TouchTheBeat/issues/72).

**Comment by ErdnussFlipS** [comment]
Check if the audio entry in audio table is correct

**Comment by ErdnussFlipS** [comment]
Checked: Audio entry in table is correct.

**Comment by hstolte** [comment]
As found in issue https://github.com/TouchTheBeat/TouchTheBeat/issues/74, the ``streamURL`` gets also changed by the backend, but it shouldn't. 

When sending a new levelto the backend via ``POST level``, the ``streamURL`` value is a ``https`` url. Once the level is retrieved again (via ``GET level``), the value of ``streamURL`` has changed to a ``http`` url. This was causing a bug due to the browsers security policies.

This behaviour seems to have changed recently, because there was no such error a few weeks ago when using the client over ``https``.

**Comment by ErdnussFlipS** [comment]
I've tested it with latest client and backend:
the response of a new level by fetching it with GET level is the following. I can no no anomalies found.
```
{
    "data": {
        "id": "testlevel-2",
        "name": "testlevel-2",
        "tags": [],
        "audio": {
            "artist": "Foster The People",
            "title": "Pumped Up Kicks",
            "duration": 238379,
            "streamUrl": "https://api.soundcloud.com/tracks/13471671/stream",
            "permalinkUrl": "http://soundcloud.com/fosterthepeoplemusic/pumpedupkicks",
            "timeLastRefresh": "0000-00-00 00:00:00"
        },
        "visuals": {},
        "gameObjects": [
            {
                "type": "Tap",
                "x": 130,
                "y": 650,
                "tapTime": 7.9786666666667,
                "shape": {
                    "type": "circle",
                    "size": "medium"
                }
            }, [...]
        ],
        "timeCreated": "2015-02-03 10:53:20",
        "timeLastModified": "2015-02-03 10:53:20",
        "owner": {
            "id": "3a10c00f-021a-4aa3-9900-5bdd4415c469",
            "email": "test@test.de",
            "username": "test",
            "homepage": "",
            "gravatar": "//www.gravatar.com/avatar/f84d37ce99493155ee296c2b746191d0?d=mm"
        },
        "playCounter": 0
    },
    "error": null,
    "error_data": null,
    "error_message": null
}
```

**Comment by hstolte** [comment]
@ErdnussFlipS  I also tested it again with the latest client and backend. The properties still get changed during ``POST``.  Take a look at the attached log file:

[issue53.har](https://files.zenhub.io/54d4a3971a9f2bbc5208d133) e.g. with [HAR Analyzer](https://toolbox.googleapps.com/apps/har_analyzer/)

I think this is also causing the "http https" bug within the client (https://github.com/TouchTheBeat/TouchTheBeat/issues/74).

**Comment by ErdnussFlipS** [comment]
Ah, that is not a bug.
If you post an level with an already existing audio permalink in storage, the audio entry in storage is not updated. We have that determined at the begin of our work.
But I want to add an auto update feature, if the last refresh is to old.

In your case, an audio entry with the permalink already exsits in the mysql db and so the audio information from db are used.

The 'https' "bug" in https://github.com/TouchTheBeat/TouchTheBeat/issues/74 is the same as this, because the stream link in db is an http link.

**Comment by hstolte** [comment]
@ErdnussFlipS I understand that the audio entry is only saved once within the database and an entry gets retrieved later again, but the values of this single audio entry are still wrong values and not only outdated values:

> The ``audio.title`` attribute seems to have the value of the original SoundCloud resources ``permalink``attribute instead of the ``title`` attribute. Also, the ``audio.artist`` attribute has the value of ``user.permalink`` instead of ``user.username``. The ``audio.duration`` attribute has a completely different value (I have no idea of its origin.).

This wrong interpretation of the original SoundCloud resource must have happened somewhere when creating the original audio entry and that is why I think this issue is a bug...

**Comment by ErdnussFlipS** [comment]
The level you posted has an audio entry, which has test data in storage, so the data is correct.
